FROM ruby:3.4.2-slim

RUN apt-get update -y && \
    apt-get install -y build-essential \
    libmariadb-dev \
    libyaml-dev \
    curl \
    git \
    vim

WORKDIR /app

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN bundle install

COPY . /app
