name: Backend CI
on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "backend/**"

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "dummy"
