# TODO: cursorに生成したものなので精査する
name: Frontend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Biome CI
        run: npm run ci

      - name: Build
        run: npm run build 
